### ISSUE TITLE
What about license?

### ISSUE THREAD

**Issue by natter1** [birkenfeld/ipython-physics#2]
I have written two tools to read in and process binary Nanoindenter- and AFM-data. To prevent user errors due to wrong units, I'm considering to implement physical values as values with unit. When looking for solutions, I stumbbled over this project. But I'm not sure, under what conditions I can use this package? Or maybe even just use a moddified physics.py (I don't need ipyton support) in my projects? My projects both use MIT-license.

**Comment by birkenfeld** [comment]
"in the public domain" means that there is no license conditions attached - feel free to use it any way you need.
